### ISSUE TITLE
[Bug]: rounding issue in longitude when exporting config

### ISSUE THREAD

**Issue by Wireheadbe** [meshtastic/python#572]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.3.9.f06c56a

### Description

When storing location as:
```
location:
  alt: xx
  lat: xx.xxxxx
  lon: 3.17491
```
Upon reading back the longitude, either in the Python CLI or the Android App, the result is:
```
location:
  alt: xx
  lat: xx.xxxxx
  lon: 3.1749099999999997
```
I suspect this also causes certain settings to not get saved / applied. This also happens on e.g. 2.3.7.30fbcab
