### ISSUE TITLE
[Bug]: Using yaml file to configure "modemPreset" and "region" causes the settings not to be applied.

### ISSUE THREAD

**Issue by Wireheadbe** [meshtastic/python#573]
using ``` meshtastic --host xxx.xxx.xxx.xxx --configure file.yaml```

With the following lora config:
```
config:
  bluetooth:
    enabled: true
    fixedPin: 123456
  device:
    nodeInfoBroadcastSecs: 10800
    role: CLIENT
    serialEnabled: true
  display:
    screenOnSecs: 600
  lora:
    hopLimit: 20
    modemPreset: LONG_SLOW
    region: EU_433
    txPower: 20
```
.. the "modemPreset" and "region" do not get applied on a freshly "wiped and flashed" device.

Hardware:
Heltec v3.1

Firmware:
2.3.7.30fbcab

Meshtastic Python API:
2.3.8
