### ISSUE TITLE
[Bug]:  export -import  function not include some parameter

### ISSUE THREAD

**Issue by bv3un** [meshtastic/python#575]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.3.9.f06c56a

### Description

Export and import function not include some parameter like GPS position ,NTP server , licensed amateur radio.thus after firmware upgrade and import config need to setup again

**Comment by ianmcorvidae** [comment]
NTP server is exported by `--export-config`, as is fixed position. I'm not sure where you're seeing it not export position, though it may not do so if you aren't using fixed position (since it wouldn't be useful to do so anyway). It does appear that the `is_licensed` field isn't exported along with the other ownership fields, though. Position precision only needs to be exported in a couple places. One is in the mqtt settings under mapReportSettings, where it is; the other is in channel settings, which is included within the channel URL. Within `--info`, position and altitude will be within the `nodes` data structure -- they're not configuration parameters in the same way other things are.

Other than the is_licensed field I don't think there's anything here to fix.

**Comment by bplein** [comment]
Thank you for responding so quickly!

For `--export-config`, `fixedPosition: <boolean>` is exported, but not the actual position information. This means that setting a fixed position on a node is not backed up, and replacing or re-imaging that node, the full configuration cannot be restored.

Example from my export
```
  position:
    broadcastSmartMinimumDistance: 100
    broadcastSmartMinimumIntervalSecs: 60
    fixedPosition: true
    gpsUpdateInterval: 120
    positionBroadcastSecs: 10800
    positionBroadcastSmartEnabled: true
    positionFlags: 3
```

I found this by having to restore a setting to a node, where i have a fixed position that is not exactly where the node is located. I checked from another node, and it was reporting the position of my phone, not the expected values from my previous `--setlat` etc.
